### PR TITLE
delay DR

### PR DESCRIPTION
**Pull request by nimeji**
https://www.raidbots.com/simbot/report/mWUHiBaxNYGNJXtStU36it

### CODE REVIEW

**Comment by nimeji** [comment]
https://www.raidbots.com/simbot/report/9czojtESmFnxD8wFDLvwCs/simc

**Comment by Krealle** [comment]
WIth your changes, if you turn off delay in some cases it's a loss for AoE, bigger if you play without vola/add enough targets.
Starts to happen on 5T and above.
Might be worth to keep old logic for `next_dragonrage` for aoe if delay is turned off? (3t+)

EoI ST build:
https://www.raidbots.com/simbot/report/h4ex7PTuEDD1Jxs7crPhyw
EoI ST build with vola:
https://www.raidbots.com/simbot/report/6qXXSw9PZEAshNhYPUHtzG
AoE build 6T:
https://www.raidbots.com/simbot/report/5nU7EtXdozeZMhqV19Mupp
AoE Build 5T:
https://www.raidbots.com/simbot/report/uGStgbuSpZeUm11DZoSpnJ
AoE Build 4T:
https://www.raidbots.com/simbot/report/ftc9zyCvZwebkpypnXGD4B
AoE build 3T:
https://www.raidbots.com/simbot/report/sHgsqQP89ZvzcswzS8KauN

On 6T with Snapfire build (-Power Swell) delay becomes a loss somehow (could prolly just take the L on this one, seems to be the only build becomes loss with delay):
https://www.raidbots.com/simbot/report/rk4vMdwJqV66K6te2DMR8H
Above build (-Snapfire +Power swell) now a gain again:
https://www.raidbots.com/simbot/report/cgH6twRAcsWHwRqvCSpyae
Snipfire+EBF:
https://www.raidbots.com/simbot/report/x3iYCnHfbwzruY1PC2URFg

**Comment by nimeji** [comment]
Thanks for checking this. This was intended to only affect ST for now so it seems I have missed that empower still depend on next_dragonrage for AOE too. Whats interesting is that because of the way DR is handled in AOE it won't actually get delayed right now, so the DPS gain we see probably comes from holding empowers for DR (which I thought wasn't a gain?). I'll try to make this DPS neutral at least and delaying should obviously be supported for AOE too

**Comment by nimeji** [comment]
After some more testing the dps gain is coming from using deep breath on pull

**Comment by nimeji** [comment]
# Changes excluding Deep Breath on pull
ST: https://www.raidbots.com/simbot/report/7AvfkydXutmHXrJEN4YPhz
3T: https://www.raidbots.com/simbot/report/v6LbTsQB7PxTZi7Jox8f7Q
4T: https://www.raidbots.com/simbot/report/u1yfhf76Tn73BveHQHWvon
5T: https://www.raidbots.com/simbot/report/b28iK9aMpwqWfJM1Bzwfq9
6T: https://www.raidbots.com/simbot/report/6Hg5ichNz9LVqB9ZFv4MSr

# Changes with Deep Breath on pull
ST: https://www.raidbots.com/simbot/report/59Hb2ksYamXSqMEJ8pRDeH
3T: https://www.raidbots.com/simbot/report/fwX3j8C6Xc7sLVmNytpx8P
4T: https://www.raidbots.com/simbot/report/qCmzTevDCUNozxdFpBq2JW
5T: https://www.raidbots.com/simbot/report/q3MUjaqdSJrwft4Q7U4vSV
6T: https://www.raidbots.com/simbot/report/3mXRiqjt3uaJJGwNY6KXLR

# Delay vs no delay
ST: https://www.raidbots.com/simbot/report/keZKLqw9X56pW9ztRoDWvV
3T: https://www.raidbots.com/simbot/report/t8Jr37SaJpdC3QyJt4tNDR
4T: https://www.raidbots.com/simbot/report/agS8W5fFn65MtGEzdzn9Mc
5T: https://www.raidbots.com/simbot/report/few1D4DZaKCFaHeAAYXHZ5
6T: https://www.raidbots.com/simbot/report/mNesfeu1nqCcwxxXdu3iLy

**Comment by nimeji** [comment]
Here are some more sims:

## 1 minute
### Changes with Deep Breath on pull
- ST: https://www.raidbots.com/simbot/report/sy2GzJBG44KWmK9tWGnZAq
- 3T: https://www.raidbots.com/simbot/report/phoAgk596Yi7bcdxvuhBL3
- 4T: https://www.raidbots.com/simbot/report/bYHowvNv4MWGqJjaXxFsGV
- 5T: https://www.raidbots.com/simbot/report/bXmEXesa5ZRDJejewGrBwb
- 6T: https://www.raidbots.com/simbot/report/w4GDus35FBD8f9pELHBcRJ

### Delay vs no delay
This should show no difference because we use DR on pull together with lust
- ST: https://www.raidbots.com/simbot/report/dSd6w4E4AhobAS4LXG1oHL
- 3T: https://www.raidbots.com/simbot/report/tfmZRRnVpm4XGVUgu6sTBT
- 4T: https://www.raidbots.com/simbot/report/5rxpixw6GMGa5vJ4HrkbKh
- 5T: https://www.raidbots.com/simbot/report/fHFrSgXxDuzunNbJQFsFpj
- 6T: https://www.raidbots.com/simbot/report/cJfnvSCkJt1TGHuqUPnf5G

## 2 minutes
### Changes with Deep Breath on pull
- ST: https://www.raidbots.com/simbot/report/wnM95z8LBoVS2TRfPWmjDq
- 3T: https://www.raidbots.com/simbot/report/3qWapwapCFRor74CYLWKXt
- 4T: https://www.raidbots.com/simbot/report/2Z88pQnLRqs4zWUUJSZiYQ
- 5T: https://www.raidbots.com/simbot/report/gcCPbfvaJPLUw2uMnp9Yc5
- 6T: https://www.raidbots.com/simbot/report/nsakyzn1Fy3x3bHNMqqL9e

### Delay vs no delay
This should show no difference because we use DR on pull together with lust
- ST: https://www.raidbots.com/simbot/report/oUa8xDPcQ5shmzepK4BrNL
- 3T: https://www.raidbots.com/simbot/report/taNrqMyVX1z6FWUaKor6aR
- 4T: https://www.raidbots.com/simbot/report/ecaATnPFW4BJNFt4x8FMKj
- 5T: https://www.raidbots.com/simbot/report/uTWyirh2WsZCiLYD8nZcAo
- 6T: https://www.raidbots.com/simbot/report/s5mV1HungkBrJEfuE3RD61

## 4 minutes
### Delay vs no delay
- ST: https://www.raidbots.com/simbot/report/azYiVUqGr4QmsjooEtQkeJ
- 6T: https://www.raidbots.com/simbot/report/nASGjEiiTZn7Wi6obQFxbg

**Pull request closed without merging**
